server:
  port: 5005

spring:
  application:
    name: flight-ops-service

  datasource:
    url: jdbc:mysql://localhost:3306/airline_flight_db
    username: root
    password: "@Durant333"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true